#!/usr/bin/env python3
"""Regenerate sitemap.xml from the HTML pages at the repository root.

Run it directly to rewrite sitemap.xml, or with --check to exit non-zero when
the committed sitemap is out of date (used by CI on pull requests).

A page is included unless it is excluded below or carries a noindex robots tag.
Its <link rel="canonical"> is the authoritative URL when present; otherwise the
URL is derived from the filename. <lastmod> comes from the file's last commit.
"""

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent

# Pages that should never appear in the sitemap.
EXCLUDE = {"404.html"}

# Per-page hints. Anything not listed here falls back to DEFAULT_HINT.
HINTS = {
    "index.html":     ("weekly",  "1.0"),
    "platform.html":  ("weekly",  "0.9"),
    "about.html":     ("monthly", "0.8"),
    "volunteer.html": ("monthly", "0.7"),
    "lawn.html":      ("monthly", "0.7"),
    "donate.html":    ("monthly", "0.7"),
}
DEFAULT_HINT = ("monthly", "0.5")

CANONICAL_RE = re.compile(r'<link\s+rel="canonical"\s+href="([^"]+)"', re.I)
NOINDEX_RE = re.compile(r'<meta\s+name="robots"[^>]*content="[^"]*noindex', re.I)


def base_url() -> str:
    """The site's origin, taken from CNAME so the two can never drift apart."""
    cname = ROOT / "CNAME"
    if cname.exists():
        host = cname.read_text(encoding="utf-8").strip()
        if host:
            return f"https://{host}"
    raise SystemExit("CNAME is missing or empty; cannot determine the site URL")


def last_modified(path: Path) -> str:
    """Date of the file's most recent commit, falling back to its mtime."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cI", "--", path.name],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
        if out:
            return out[:10]
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    return datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).date().isoformat()


def page_url(path: Path, html: str, base: str) -> str:
    m = CANONICAL_RE.search(html)
    if m:
        return m.group(1)
    return f"{base}/" if path.name == "index.html" else f"{base}/{path.name}"


def build() -> str:
    base = base_url()
    entries = []

    for path in sorted(ROOT.glob("*.html")):
        if path.name in EXCLUDE:
            continue
        html = path.read_text(encoding="utf-8")
        if NOINDEX_RE.search(html):
            continue
        changefreq, priority = HINTS.get(path.name, DEFAULT_HINT)
        entries.append((page_url(path, html, base), last_modified(path), changefreq, priority))

    # Highest priority first, then alphabetically, so the file has a stable order.
    entries.sort(key=lambda e: (-float(e[3]), e[0]))

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by scripts/generate_sitemap.py. Do not edit by hand. -->',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for loc, lastmod, changefreq, priority in entries:
        lines += [
            "  <url>",
            f"    <loc>{escape(loc)}</loc>",
            f"    <lastmod>{lastmod}</lastmod>",
            f"    <changefreq>{changefreq}</changefreq>",
            f"    <priority>{priority}</priority>",
            "  </url>",
        ]
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if sitemap.xml is out of date instead of rewriting it")
    args = parser.parse_args()

    target = ROOT / "sitemap.xml"
    generated = build()
    current = target.read_text(encoding="utf-8") if target.exists() else None

    if args.check:
        if current != generated:
            print("sitemap.xml is out of date; run scripts/generate_sitemap.py", file=sys.stderr)
            return 1
        print("sitemap.xml is up to date")
        return 0

    if current == generated:
        print("sitemap.xml is already up to date")
        return 0

    target.write_text(generated, encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} ({generated.count('<url>')} urls)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
